services:
  postgres:
    image: postgres:16
    container_name: wex-postgres

    environment:
      POSTGRES_DB: wex_purchase
      POSTGRES_USER: wex_user
      POSTGRES_PASSWORD: wex_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: