spring.application.name=purchase-transaction-service

spring.datasource.url=jdbc:postgresql://localhost:5432/wex_purchase
spring.datasource.username=wex_user
spring.datasource.password=wex_password

spring.jpa.hibernate.ddl-auto=validate